Sl 6809
sima-land/delivery-php-calculator pull request #3
Opened 2017-01-31 11:58 UTC by danilfromekb

2017-01-31 12:06 UTC, pahanini commented on src/Calculator.php
> +    const MOSCOW_POINT_DELIVERY_PRICE = 1068.75;
По-моему это ответственность объекта реализующего SettlementInterface

2017-01-31 12:09 UTC, pahanini commented on src/ItemInterface.php
> +    public function isPaidDeliveryEkb() : bool;
Зачем? Есть же isPaidDelivery?

2017-01-31 12:13 UTC, pahanini commented on src/Calculator.php
> +            $volumeFactor = $itemPackingVolumeFactor ?: $packingVolumeFaktor->getFactor($item->getProductVolume());
Тоже непонятно зачем это? Есть же у $item->getPackingVolumeFactor();

2017-01-31 12:14 UTC, pastuhov commented on src/PackingVolumeFaktor.php
> +/**
лучше убрать

2017-01-31 12:15 UTC, pahanini commented on src/PackingVolumeFaktor.php
> +/**
И кстати factor

2017-01-31 12:16 UTC, pahanini commented on src/Calculator.php
> +    protected function setDeliveryPricePerUnitVolume(SettlementInterface $settlement, bool $forMoscowPoint)
Зачем эта функция?

2017-01-31 12:22 UTC, danilfromekb commented on src/ItemInterface.php
> +    public function isPaidDeliveryEkb() : bool;
Доставка в екб по умолчанию бесплатная, даже если она платная для других городов

2017-01-31 12:24 UTC, danilfromekb commented on src/Calculator.php
> +            $volumeFactor = $itemPackingVolumeFactor ?: $packingVolumeFaktor->getFactor($item->getProductVolume());
Есть также общий фактор, работающий в случае если в item фактор не задан

2017-01-31 12:26 UTC, danilfromekb commented on src/Calculator.php
> +    protected function setDeliveryPricePerUnitVolume(SettlementInterface $settlement, bool $forMoscowPoint)
Для москвы может быть фиксированная цена

2017-01-31 12:28 UTC, pahanini commented on src/Calculator.php
> +            $volumeFactor = $itemPackingVolumeFactor ?: $packingVolumeFaktor->getFactor($item->getProductVolume());
Мне кажется расчет фактора по умолчанию, это обязанность объекта реализующего интерфейс. Калькулятор должен лишь убедиться, что переданные данные валидны

2017-01-31 12:30 UTC, pahanini commented on src/ItemInterface.php
> +    public function isPaidDeliveryEkb() : bool;
То же самое, пусть объект реализующий SettlementInterface для екб возвращает 0, представь что еще у 10 городов будет бесплатная доставка, будем делать еще 10 методов?

2017-01-31 12:34 UTC, pastuhov commented on src/PackingVolumeFaktor.php
> +class PackingVolumeFaktor
faCtor

2017-01-31 14:19 UTC, danilfromekb commented on src/ItemInterface.php
> +    public function isPaidDeliveryEkb() : bool;
Товар решает платный он для екб или нет

2017-02-01 12:34 UTC, pastuhov requested changes

2017-02-01 12:34 UTC, pastuhov commented on README.md
> +Чтобы посчитать стоимость доставки для Москвы нужно передать в метод calculate
старое

2017-02-01 12:34 UTC, pastuhov commented on src/Calculator.php
> +    protected $additionalResult;
старое?

2017-02-01 12:34 UTC, pastuhov commented on src/ItemTrait.php
> + * Реализует ItemInterface
частично

2017-02-01 12:34 UTC, pastuhov commented on src/SettlementInterface.php
> +    public function switchForMoscowPoint($forMoscowPoint = true);
что это?

2017-02-01 12:34 UTC, pastuhov commented on src/SettlementTrait.php
> +    public function switchForMoscowPoint($forMoscowPoint = true)
как то плохо это все выглядит

2017-02-01 12:34 UTC, pastuhov commented on src/SettlementTrait.php
> +    public function switchForMoscowPoint($forMoscowPoint = true)
можно же простое публичное св-во сделать
public isPoint к примеру и будет визуально легкче

2017-02-01 15:39 UTC, danilfromekb commented on README.md
> +Чтобы посчитать стоимость доставки для Москвы нужно передать в метод calculate
fixed

2017-02-01 15:39 UTC, danilfromekb commented on src/Calculator.php
> +    protected $additionalResult;
fixed

2017-02-01 15:40 UTC, danilfromekb commented on src/ItemTrait.php
> + * Реализует ItemInterface
fixed

2017-02-01 15:40 UTC, danilfromekb commented on src/SettlementInterface.php
> +    public function switchForMoscowPoint($forMoscowPoint = true);
fixed

2017-02-01 15:40 UTC, danilfromekb commented on src/SettlementTrait.php
> +    public function switchForMoscowPoint($forMoscowPoint = true)
fixed

2017-02-06 08:24 UTC, pahanini commented on README.md
> +calculate в качестве объекта города нужно передать объект класса
предложение не согласовано

2017-02-06 08:25 UTC, pahanini commented on src/Calculator.php
> +    const TOTAL_DISCOUNT_VALUE = 0;
Так может если скидки нет то уберем это?

2017-02-06 08:38 UTC, danilfromekb commented on README.md
> +calculate в качестве объекта города нужно передать объект класса
fixed

2017-02-06 08:38 UTC, danilfromekb commented on src/Calculator.php
> +    const TOTAL_DISCOUNT_VALUE = 0;
fixed

2017-02-06 08:57 UTC, pahanini commented on src/ItemTrait.php
> +    abstract public function getPackingVolumeFactorComponent() : PackingVolumeFactor;
А зачем в трейте описания абстрактных методов?

2017-02-06 08:57 UTC, pahanini commented on src/PackingVolumeFactor.php
> +namespace SimaLand\DeliveryCalculator;
models не?

2017-02-10 05:01 UTC, merged